# code in init_unreal.py wil run on startup if the plugin is enabled
import dependencies_installer
dependencies_installer.install_dependencies()

import unreal


section_name = 'Plugins'
se_command = 'import my_module;w = my_module.show()'  # todo replace with your code
label = 'My Plugin'
tooltip = "my tooltip"


def create_script_editor_button():
    """Add a tool button to the tool bar"""
    menus = unreal.ToolMenus.get()
    level_menu_bar = menus.find_menu('LevelEditor.LevelEditorToolBar.PlayToolBar')
    level_menu_bar.add_section(section_name=section_name, label=section_name)

    entry = unreal.ToolMenuEntry(type=unreal.MultiBlockType.TOOL_BAR_BUTTON)
    entry.set_label(label)
    entry.set_tool_tip(tooltip)
    entry.set_icon('EditorStyle', 'DebugConsole.Icon')
    entry.set_string_command(
        type=unreal.ToolMenuStringCommandType.PYTHON,
        custom_type=unreal.Name(''),  # not sure what this is
        string=se_command
    )
    level_menu_bar.add_menu_entry(section_name, entry)
    menus.refresh_all_widgets()


def add_cmd_to_menu(label=None, command=None, tooltip=None, icon=None):
    unreal_menus = unreal.ToolMenus.get()
    parent_menu = unreal_menus.find_menu("LevelEditor.MainMenu.Tools")

    # name kwargs needs to be unique! if not set, it's autogenerated
    entry = unreal.ToolMenuEntry(
        type=unreal.MultiBlockType.MENU_ENTRY,
        insert_position=unreal.ToolMenuInsert("", unreal.ToolMenuInsertType.FIRST),
    )
    if label:
        entry.set_label(label)
    if command:
        entry.set_string_command(
            type=unreal.ToolMenuStringCommandType.PYTHON,
            string=command,
            custom_type=unreal.Name("_placeholder_"),
        )
    if tooltip:
        entry.set_tool_tip(tooltip)
    if icon:
        entry.set_icon(icon)

    parent_menu.add_menu_entry("Configuration", entry)


# create_script_editor_button()  ## uncomment to add a button to the toolbar to launch your tool
add_cmd_to_menu(label=label, command=se_command, tooltip=tooltip)
print("My plugin is enabled")
